### PR TITLE
fix: system logo being hidden on recalbox

### PR DESCRIPTION
**Pull request by arnaudschlupp**
Not sure if it is going to break or not on Retropie though 🤔

### CODE REVIEW

**Comment by anthonycaccese** [comment]
I am not sure Retropie supports @system without .theme being appended.  Will check this this week.  If Retropie doesn't support it I would be ok with you forking it to a recalbox specific theme if that works.

**Comment by anthonycaccese** [comment]
@arnaudschlupp unfortunately this doesn't work under Retropie so I won't be able to accept this commit as-is.  Thinking through options - maybe we could add this as separate theme.xml called theme-recalbox.xml? (that I figure would require recalbox users to make a manual change when using it) Or maybe forking the base theme and calling it ES Theme Artbook Pocket for RecalBox.  The alternative I could look at is changing the theme to not use variables at all (which would make it cross compatible) but I am not sure when I would be able to get to that.

**Comment by arnaudschlupp** [comment]
Thanks for the quick reply @anthonycaccese and congrats on the beautiful themes you created so far! I think forking it would make sense here indeed 👍. As the change is platform specific it would avoid to "pollute" each version when diversion like this one appears. Even though this one is quite small now we never know what can change 🤷

**Comment by anthonycaccese** [comment]
Awesome @arnaudschlupp that sounds good.  Please let me know the fork details when you have them and I'll a reference to mine to point recalbox users in that direction.

**Pull request closed without merging**
